repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: local
    hooks:
      - id: yamllint
        name: yamllint
        entry: yamllint --strict
        language: system
        types: [yaml]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]

      - id: terraform-fmt
        name: terraform fmt
        entry: terraform fmt -recursive -check -diff
        language: system
        files: \.tf$
        pass_filenames: false
